### ISSUE TITLE
python3

### ISSUE THREAD

**Issue by davendw49** [shagunsodhani/powerlaw#1]
hava some trouble over python3 env.
like:
maxint and maxsize
and 
ZeroDivisionError: division by zero
both in regression.py

**Comment by shagunsodhani** [comment]
I have fixed these issues. Could you please try with the new code. If it still does not work, please share the code that gives you the error.

**Comment by davendw49** [comment]
> I have fixed these issues. Could you please try with the new code. If it still does not work, please share the code that gives you the error.

thank you~ problem solved.
